services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-db
    restart: always
    env_file: 
      - .env  # Подключение файла .env
    ports:
      - "${POSTGRES_PORT}:5432"  # Используем переменную из .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
